.TH "main.cpp" 3 "Wed Sep 11 2013" "MARCS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.cpp \- 
.SH SYNOPSIS
.br
.PP
.SH "Function Documentation"
.PP 
.SS "int main (intargc, char *argv[])"

.PP
.nf
5 {
6     QApplication a(argc, argv);
7     MARCS w;
8 
9     w\&.show();
10 
11     return a\&.exec();
12 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for MARCS from the source code\&.
