.TH "video.cpp" 3 "Wed Sep 11 2013" "MARCS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
video.cpp \- 
.SH SYNOPSIS
.br
.PP
.SH "Variable Documentation"
.PP 
.SS "bool affichageList"

.SS "GeoDataDocument* document"

.SS "QString fileOpened"

.SS "GeoPainter* gp"

.SS "QString lastMap"

.SS "QString lastMission"

.SS "QListView* m_listView"

.SS "RoutingManager* manager"

.SS "RoutingManager* manager_smallMap"

.SS "int num_waypoint = 0"

.SS "char* numWpText = new char[32]"

.SS "bool open = false"

.SS "GeoDataPlacemark* place"

.SS "QString qstr"

.SS "RouteRequest* request"

.SS "RouteRequest* request_smallMap"

.SS "string temp"

.SS "GeoDataCoordinates* tempo"

.SS "string textNumWaypoint"

.SS "QList<\fBwaypoint\fP* > wpListOpen"

.SS "QList< \fBwaypoint\fP* > wpListSave"

.SH "Author"
.PP 
Generated automatically by Doxygen for MARCS from the source code\&.
